version: '3'

volumes:
  elasticsearch716-data:

services:
  elasticsearch716:
    build:
      context: ./elasticsearch/7.16
    environment:
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch716-data:/usr/share/elasticsearch7/data
    ports:
      - "9716:9200"
      - "9816:9300"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.0
    depends_on:
      - elasticsearch716
      - apm-server
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch716:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch716:9200
      - xpack.apm.enabled=false
      - xpack.encryptedSavedObjects.encryptionKey=

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.13.0
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    depends_on:
      - elasticsearch716
    ports:
      - "8200:8200"
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch716:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
